---
- hosts: "{{ target_host  }}"
  gather_facts: true
  tasks:
    - name: Install APT packages to use a repository over HTTPS
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: yes
        cache_valid_time: 86400 # cache for 1 day
      become: true

    - name: Create APT's keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
      become: true

    - name: Add Docker's official GPG key
      ansible.builtin.shell: 
        cmd: "rm -rf /etc/apt/keyrings/docker.gpg; curl -fsSL https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
        creates: /etc/apt/keyrings/docker.gpg
      become: true

    - name: Setup the repository
      shell: >
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ansible_distribution | lower}} $(lsb_release -cs) stable"
          | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: true

    - name: update cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: Install Docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - docker-compose-plugin
        update_cache: yes
      become: true

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
      become: true

    - name: add user to docker group
      ansible.builtin.user:
        name: "{{ansible_user_id}}"
        groups: docker
        append: yes
      become: true

