---
- hosts: servers
  vars:
    apikey: hoge
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false

  tasks:
    - name: check mackerel installed
      stat:
        path: /etc/mackerel-agent/mackerel-agent.conf
      register: file

    - debug:
        msg: "{{file.stat.exists}}"

    - name: install mackerel-agent debian
      shell: wget -q -O - https://mackerel.io/file/script/setup-all-apt-v2.sh | MACKEREL_APIKEY='{{ apikey }}' sh
      when: file.stat.exists == False
